agent_start: [0.0, 0.0]
named_areas:
  - name: Base
    points:
      - [1.0, 1.0]
      - [3.0, 1.0]
      - [3.0, 3.0]
      - [1.0, 3.0]
    color: [255, 0, 0]
  - name: Alpha
    points:
      - [5.0, 3.0]
    color: [0, 0, 255]
  - name: Bravo
    points:
      - [5.0, -1.0]
    color: [0, 255, 0]
